/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class TwoByTwoMatrixTest {
    @Test public void testSomeLibraryMethod() {
        TwoByTwoMatrix classUnderTest = new TwoByTwoMatrix();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
